name: ci-feature

on:
  push:
    branches:
      - 'feature/**'
      - 'dependabot/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: run tests with docker-compose
        run: |
          ls -la \
          && docker context list \
          && docker-compose version \
          && docker compose version \
          && docker compose -f docker-compose.test.yml up --build sut --exit-code-from sut

# Don't push feature builds to docker hub
