name: ci-main

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: run tests with docker-compose
        run: |
          ls -la \
          && docker context list \
          && docker-compose version \
          && docker compose version \
          && docker compose -f docker-compose.test.yml up --build sut --exit-code-from sut
      -
        name: run dockerx to build and push
        run: |
          ls -la && docker context list && docker buildx build --build-arg GITHUB_REPOSITORY=${GITHUB_REPOSITORY} --build-arg GITHUB_REF_NAME=${GITHUB_REF_NAME} --build-arg GITHUB_RUN_ID=${GITHUB_RUN_ID} --build-arg GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER} --build-arg GITHUB_SHA=${GITHUB_SHA} --platform linux/amd64,linux/arm64 --tag michaelmworthington/docker-test-ghas:latest .
