# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which checks out the code, builds a container
# image using Docker and scans that image for vulnerabilities using
# Snyk. The results are then uploaded to GitHub Security Code Scanning
#
# For more examples, including how to limit scans to only high-severity
# issues, monitor images for newly disclosed vulnerabilities in Snyk and
# fail PR checks for new vulnerabilities, see https://github.com/snyk/actions/

name: Docker Container Scan Broken

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '18 5 * * 1'

permissions:
  contents: read

jobs:
  docker-scan-broken:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build a Docker image
    #   run: docker build -t your/image-to-test .

    - name: Build with Buildkit
      uses: docker/build-push-action@v3
      with:
        tags: your/image-to-test
        load: true

    - name: Docker Image Inspect
      run: |
        docker image inspect your/image-to-test

#        && wget -O ~/.docker/cli-plugins/docker-scan https://github.com/docker/scan-cli-plugin/releases/latest/download/docker-scan_linux_amd64
#        && docker scan --accept-license --token ${{ secrets.SNYK_TOKEN }} --json --file ./Dockerfile your/image-to-test > docker-scan.sarif 2>&1
    - name: Docker Scan CLI
      run: |
        mkdir -p ~/.docker/cli-plugins \
        && curl https://github.com/docker/scan-cli-plugin/releases/latest/download/docker-scan_linux_amd64 -L -s -S -o ~/.docker/cli-plugins/docker-scan \
        && chmod +x ~/.docker/cli-plugins/docker-scan \
        && cp ./Dockerfile /tmp \
        && docker scan --accept-license --token ${{ secrets.SNYK_TOKEN }} --file /tmp/Dockerfile your/image-to-test

    - name: Current Directory
      run: |
        ls -la \
        && echo "######################" \
        && ls -la ~/.docker/cli-plugins

    - name: Docker Scan Sarif Contents
      run: |
        cat docker-scan.sarif

    # - name: Upload result to GitHub Code Scanning
    #   uses: github/codeql-action/upload-sarif@v2
    #   if: always()
    #   with:
    #     sarif_file: docker-scan.sarif
